Fix auto zoom
FlockOfBirds/google-maps pull request #5
Opened 2017-08-22 08:46 UTC by mistaguy

2017-08-22 10:45 UTC, djkwagala requested changes

2017-08-22 10:45 UTC, djkwagala commented on src/components/Map.ts
> +                            minZoom: 2,
Why is this set as 2 instead of 1. Please add a comment in the code

2017-08-22 10:45 UTC, djkwagala commented on src/GoogleMaps.xml
> +        <property key="autoZoom" type="boolean" defaultValue="true">
Add visibilityProps in src/GoogleMaps.webmodeler.ts to hide zoom configurations when autoZoom is true.

2017-08-23 06:48 UTC, mistaguy commented on src/GoogleMaps.xml
> +        <property key="autoZoom" type="boolean" defaultValue="true">
Whether autozoom is true or false the zoom control will have to be shown if  it is enabled because auto zoom is executed only on first rendering

2017-08-31 11:01 UTC, closed without merging